database/urls.py
# -*- coding: utf-8 -*-
"""
# @Time    : 2021/6/11 下午10:02
# @Author  : Jiacai Yi
# @FileName: urls.py
# @E-mail  ：1076365758@qq.com
"""
from django.urls import path, include
from . import views

app_name = 'database'
urlpatterns = [
    path('property/', views.property, name="property"),
    path('property-data-source/', views.peroperty_datasource, name='peroperty_data_source'),
    path('gdetail/<idx>/', views.tranformation_detail, name='transformation_detail'),
    path('pgdetail/<idx>/', views.pre_tranformation_detail, name='pre_transformation_detail'),
    path('local-data-source/<idx>/', views.local_datasource, name='local_data_source'),
    path('plocal-data-source/<idx>/', views.pre_local_datasource, name='pre_local_data_source'),
    path('ldetail/<idx>/', views.local_detail, name='local_detail'),
    path('pldetail/<idx>/', views.pre_local_detail, name='pre_local_detail'),
    path('mmp-data-source/<idx>/', views.mmp_datasource, name='mmp_data_source'),
    path('pmmp-data-source/<idx>/', views.pre_mmp_datasource, name='pre_mmp_data_source'),
    path('mmp-ldata-source/<idx>/', views.mmp_ldatasource, name='mmp_ldata_source'),
    path('pmmp-ldata-source/<idx>/', views.pre_mmp_ldatasource, name='pre_mmp_ldata_source'),
    path('structure/', views.structure, name="structure"),
    path('structure-data-source/', views.structure_datasource, name='structure_data_source'),
    path('sdetail/<idx>/', views.structure_detail, name='structure_detail'),
    path('psdetail/<idx>/', views.pre_structure_detail, name='pre_structure_detail'),
    path('global-data-source/<idx>/', views.global_datasource, name='global_data_source'),
    path('pglobal-data-source/<idx>/', views.pre_global_datasource, name='pre_global_data_source'),
    path('ldata-source/<idx>/', views.ldatasource, name='ldatasource'),
    path('pldata-source/<idx>/', views.pre_ldatasource, name='pre_ldatasource'),
]

home/urls.py
# -*- coding: utf-8 -*-
"""
# @Time    : 2021/6/11 下午3:45
# @Author  : Jiacai Yi
# @FileName: urls.py
# @E-mail  ：1076365758@qq.com
"""
from django.urls import path, include
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name="index"),
    path('tutorial/', views.tutorials, name="tutorials"),
    path('contact/', views.contact, name="contact"),
    # path('download/', views.download, name="download"),
    path('pub/', views.publication, name="pub"),
    path('terms/', views.term, name="term"),
    path('checker/', views.checker, name="checker"),
    path('checkerCal/', views.checkercal, name='checkercal'),
    path('result-datasource/', views.result_datasource, name='result_datasource'),
    path('result/<str:filename>', views.result_file, name='result'),
    path('result/<str:filename>/<str:index>/<str:data_idx>', views.result_mol, name="result_mol"),
    path('result/<str:filename>/<str:index>/<str:data_idx>/<str:dire_idx>', views.result_mol_direct, name="result_mol"),
    path('screening/', views.final_screening, name='final_screening'),
    path('final_result/<str:filename>/<str:properties>', views.final_result_file, name='final_result'),
    path('final-result-datasource/', views.final_result_datasource, name='final_result_datasource'),
    path('s_download/', views.s_download, name="s_download"),
    path('d_download/', views.d_download, name="d_download"),
    path('d_pdf/<str:filename>/<str:index>', views.d_pdf, name="d_pdf"),
]

templates/common/backtotop.html
{% load static %}
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="shortcut icon" href="/deploy/optadmet/static/favicon.ico">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{% block title %}OptADMET{% endblock %}</title>

{#    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"#}
{#          rel="stylesheet">#}

    <link rel="stylesheet" href="{% static 'common/layui-v2.6.8/layui/css/layui.css' %}">
    <script src="{% static 'common/layui-v2.6.8/layui/layui.js' %}"></script>


    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <link rel="stylesheet" href="{% static 'common/aos/aos.css' %}">
    <link href="{% static 'common/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'common/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'common/boxicons/css/boxicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'common/glightbox/css/glightbox.min.css' %}">
    <link rel="stylesheet" href="{% static 'common/remixicon/remixicon.css' %}">
    <link rel="stylesheet" href="{% static 'common/swiper/swiper-bundle.min.css' %}">

    {% comment %} <link rel="stylesheet" href="{% static 'common/DataTables/datatables.min.css' %}"> {% endcomment %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.5/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/duyplus/fontawesome-pro/css/all.min.css">


    <script src="{% static 'common/jquery/jquery.min.js' %}"></script>
{#    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>#}
{#    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap5.min.js"></script>#}
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
    {% comment %} <script src="{% static 'common/DataTables/datatables.min.js' %}"></script> {% endcomment %}
    {#    <script src="{% static 'home/js/style.js' %}"></script>#}


    {# nav.html #}
    {% block navres %}
        {#        <link rel="stylesheet" href="{% static 'home/css/nav.css' %}">#}
    {% endblock %}

    {# footer.html #}
    <link rel="stylesheet" href="{% static 'home/css/footer.css' %}">
    {# backtotop.html #}
    {#    <link rel="stylesheet" href="{% static 'common/backtotop/css/unicons.css' %}">#}
    {#    <link rel="stylesheet" href="{% static 'common/backtotop/css/style.css' %}">#}
    {#    <script src="{% static 'common/backtotop/js/style.js' %}"></script>#}
    {##}
    {# banner.html #}
    {#    <link rel="stylesheet" href="{% static 'common/banner/css/style.css' %}">#}
    {##}
</head>
<body>

<div class="antin-container">
    {% block nav %}
        {% include 'common/nav.html' %}
    {% endblock %}
    {#    {% block banner %}#}
    {#        {% include 'share_layout/banner.html' %}#}
    {#    {% endblock %}#}

    <!--[if lt IE 7]>
    <p class="chromeframe">You are using a</p><p class="chromeframe">n <strong>outdated</strong> browser. Please <a
            href="http://browsehappy.com/">upgrade your browser</a> or <a
            href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your
        experience.</p>
    <![endif]-->

    <div class="antin-contain">
        {% block content %}
        {% endblock %}
    </div>

    {% block footer %}
        {% include 'common/footer.html' %}
    {% endblock %}

    {% include 'common/backtotop.html' %}

</div>
{#<script src="{% static 'common/jquery/jquery.min.js' %}"></script>#}
{#<script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>#}
{#<script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap5.min.js"></script>#}
<script src="{% static 'common/aos/aos.js' %}"></script>
<script src="{% static 'common/bootstrap-5.0.0-dist/js/bootstrap.min.js' %}" async="async"></script>
<script src="{% static 'common/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'common/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'common/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'common/purecounter/purecounter.js' %}"></script>
<script src="{% static 'home/js/style.js' %}"></script>



</body>
{% block script %}{% endblock %}
</html>

templates/common/footer.html
{% load static %}

<link rel="stylesheet" href="{% static 'common/footer/css/xui.css' %}">
<!-- ======= Footer ======= -->
<footer id="footer" style="">
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 footer-info">
                    <h3>About OptADMET</h3>
                    <p style="text-align: justify;color:'#CCC'">
                        OptADMET is the integrated chemical transformation rule platform covering 32 important ADMET
                        properties, which provides multiple-property rules and lead optimization direction. It is
                        believed that this webserver promises to be a powerful approach to aid multidimensional
                        optimization.</p>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Quick Links</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'home:contact' %}">Contact Us</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'home:pub' %}">Publications</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="{% url 'home:tutorials' %}">Help Tutorials</a></li>
                        <li><i class="bx bx-chevron-right"></i>
                            <script type="text/javascript"
                                    src="//rf.revolvermaps.com/0/0/9.js?i=5gsgpjluar4&amp;t=Live%20Statistics"
                                    async="async"></script>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Software</h4>
                    <table class="xtable xnobor-all">
                        <tr>
                            <td>
                                <a href="https://www.python.org/" target="_blank">
                                    <img class="img-thumbnail" src="{% static 'common/footer/imgs/python-logo.png' %}"
                                         alt="">
                                </a>
                            </td>
                            <td>
                                <a href="https://www.rdkit.org/" target="_blank">
                                    <img class="img-thumbnail" src="{% static 'common/footer/imgs/rdkit-logo.png' %}"
                                         alt="">
                                </a>
                            </td>
                            <td>
                                <a href="https://www.djangoproject.com/" target="_blank">
                                    <img class="img-thumbnail" src="{% static 'common/footer/imgs/django-logo.png' %}"
                                         alt="">
                                </a>
                            </td>
                            <td>
                                <a href="https://www.mysql.com/" target="_blank">
                                    <img class="img-thumbnail" src="{% static 'common/footer/imgs/mysql-logo.png' %}"
                                         alt="">
                                </a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            &copy; Copyright <a href="http://www.scbdd.com/" target="_blank">Xiangya
            School of Pharmaceutical Sciences,
            Central South University</a>.
            All Rights Reserved
        </div>
        {#        <div class="credits">#}
        {#            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>#}
        {#        </div>#}
    </div>
</footer><!-- End Footer -->

templates/common/nav.html
{% load static %}
<!-- ======= Header ======= -->
<header id="header" class="fixed-top d-flex align-items-center">
    <div class="layui-col-md-offset1 layui-col-md10 d-flex align-items-center justify-content-between">
        <h1 class="logo">
            <img src="{% static 'favicon.ico' %}" width="40" height="40"
                 class="d-inline-block justify-content-center align-items-center mr-2" alt="">
            <a href="{% url 'home:index' %}">OptADMET</a>
        </h1>
        <nav id="navbar" class="navbar">
            <ul>
                {% with path=request.path %}
                    <li><a class="nav-link scrollto {% if path == '/' %}active{% endif %}"
                           href="{% url 'home:index' %}"><i class="fas fa-home nav-icon"></i> Home</a></li>
                    <li><a class="nav-link scrollto {% if path == '/checker/' %}active{% endif %}"
                            href="{% url 'home:checker' %}"><i class="fas fa-fingerprint nav-icon"></i> Optimization</a>
                    </li>
                    <li class="dropdown"><a href="#"
                                            class="{% if path == '/optadmet/property/' %}active{% endif %}"><span><i
                            class="fas fa-database nav-icon"></i> Database</span>
                        <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li class=""><a href="{% url 'database:property' %}"><span>Single Property</span></a>
                            </li>
                            <li class="dropdown"><a
                                    href="{% url 'database:structure' %}"><span>Double Properties</span></a>
                            </li>
                        </ul>
                    </li>
                    {% comment %} <li><a class="nav-link scrollto {% if path == '/download/' %}active{% endif %}"
                           href="{% url 'home:download' %}"><i class="fas fa-cloud-download-alt nav-icon"></i> Download</a>
                    </li> {% endcomment %}
                    {% comment %} <li><a class="nav-link scrollto {% if path == '/pub/' %}active{% endif %}"
                        href="{% url 'home:pub' %}"><i class="fas fa-file-alt nav-icon"></i> Pubulication</a>
                    </li> {% endcomment %}
                    <li><a class="nav-link scrollto {% if path == '/tutorial/' %}active{% endif %}"
                           href="{% url 'home:tutorials' %}"><i class="fas fa-file-alt nav-icon"></i> Tutorials</a>
                    </li>
                    <li><a class="nav-link scrollto {% if path == '/contact/' %}active{% endif %}"
                           href="{% url 'home:contact' %}"><i class="fas fa-id-card nav-icon"></i> Contact</a>
                    </li>
                {% endwith %}
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->
    </div>
</header><!-- End Header -->